package com.autodeploy.service;

import com.autodeploy.model.Redireccion;
import com.autodeploy.model.Servidor;
import com.autodeploy.repository.RedireccionRepository;
import org.springframework.stereotype.Service;
import org.xbill.DNS.AAAARecord;
import org.xbill.DNS.ARecord;
import org.xbill.DNS.CNAMERecord;
import org.xbill.DNS.Lookup;
import org.xbill.DNS.MXRecord;
import org.xbill.DNS.NSRecord;
import org.xbill.DNS.Record;
import org.xbill.DNS.TXTRecord;
import org.xbill.DNS.Type;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service
public class NetworkingService {

    private static final String RUTA_REDIRECTS = "$HOME/.autodeploy/redirects.conf";

    private final RedireccionRepository redireccionRepository;
    private final ServidorService servidorService;
    private final SshCommandService sshCommandService;

    public NetworkingService(RedireccionRepository redireccionRepository,
                             ServidorService servidorService,
                             SshCommandService sshCommandService) {
        this.redireccionRepository = redireccionRepository;
        this.servidorService = servidorService;
        this.sshCommandService = sshCommandService;
    }

    public Map<String, List<String>> consultarDns(String dominio) {
        Map<String, List<String>> resultado = new HashMap<>();
        resultado.put("a", consultarRegistros(dominio, Type.A));
        resultado.put("aaaa", consultarRegistros(dominio, Type.AAAA));
        resultado.put("cname", consultarRegistros(dominio, Type.CNAME));
        resultado.put("mx", consultarRegistros(dominio, Type.MX));
        resultado.put("ns", consultarRegistros(dominio, Type.NS));
        resultado.put("txt", consultarRegistros(dominio, Type.TXT));
        return resultado;
    }

    private List<String> consultarRegistros(String dominio, int tipo) {
        try {
            Lookup lookup = new Lookup(dominio, tipo);
            Record[] registros = lookup.run();
            if (registros == null) return List.of();
            return java.util.Arrays.stream(registros)
                    .map(this::formatearRegistro)
                    .collect(Collectors.toList());
        } catch (Exception excepcion) {
            return List.of();
        }
    }

    private String formatearRegistro(Record registro) {
        if (registro instanceof ARecord r) return r.getAddress().getHostAddress();
        if (registro instanceof AAAARecord r) return r.getAddress().getHostAddress();
        if (registro instanceof CNAMERecord r) return r.getTarget().toString();
        if (registro instanceof MXRecord r) return r.getPriority() + " " + r.getTarget().toString();
        if (registro instanceof NSRecord r) return r.getTarget().toString();
        if (registro instanceof TXTRecord r) return String.join(" ", r.getStrings());
        return registro.toString();
    }

    public List<Redireccion> listarRedirecciones(String servidorId) {
        return redireccionRepository.findByServidorId(servidorId);
    }

    public Redireccion crearRedireccion(String servidorId, String origen, String destino, int codigo) {
        Servidor servidor = servidorService.obtenerPorId(servidorId);
        Redireccion nueva = new Redireccion(servidorId, origen, destino, codigo);
        Redireccion persistida = redireccionRepository.save(nueva);

        sincronizarNginxConfig(servidor);

        return persistida;
    }

    public void eliminarRedireccion(String idRedireccion) {
        Redireccion redireccion = redireccionRepository.findById(idRedireccion)
                .orElseThrow(() -> new RuntimeException("Redireccion no encontrada"));

        Servidor servidor = servidorService.obtenerPorId(redireccion.getServidorId());
        redireccionRepository.delete(redireccion);

        sincronizarNginxConfig(servidor);
    }

    private void sincronizarNginxConfig(Servidor servidor) {
        List<Redireccion> redirecciones = redireccionRepository.findByServidorId(servidor.getId());

        StringBuilder configuracion = new StringBuilder();
        configuracion.append("# Auto-generated by AutoDeploy at ").append(java.time.LocalDateTime.now()).append("\n");
        configuracion.append("# ").append(redirecciones.size()).append(" redirect(s) configured\n\n");

        for (Redireccion redireccion : redirecciones) {
            configuracion.append("server {\n");
            configuracion.append("    listen 80;\n");
            configuracion.append("    listen 443 ssl;\n");
            configuracion.append("    server_name ").append(redireccion.getHostOrigen()).append(";\n");
            configuracion.append("    return ").append(redireccion.getCodigoEstado()).append(" ").append(redireccion.getUrlDestino()).append("$request_uri;\n");
            configuracion.append("}\n\n");
        }

        String comando = "mkdir -p $HOME/.autodeploy && cat > " + RUTA_REDIRECTS + " << 'REDIRECTSEOF'\n" + configuracion.toString() + "\nREDIRECTSEOF";

        try {
            sshCommandService.ejecutarComando(servidor, comando);
        } catch (Exception ignorado) {
        }
    }

    public String leerConfigRedirects(String servidorId) {
        Servidor servidor = servidorService.obtenerPorId(servidorId);
        try {
            return sshCommandService.ejecutarComando(servidor, "cat " + RUTA_REDIRECTS + " 2>/dev/null || echo '(no redirects file yet)'");
        } catch (Exception excepcion) {
            return "(error reading redirects file)";
        }
    }
}
