spring.application.name=autodeploy

server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/autodeploy

autodeploy.cifrado.clave=YXV0b2RlcGxveS1zZWNyZXQta2V5LTMyYg==

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

